### ISSUE TITLE
Parsing of attributes in script

### ISSUE THREAD

**Issue by stursberg** [HPI-BP2017N2/Parser#10]
The parser should be able to use DataNodeSelectors from SRG and extract product attributes from content including in <script> tags.

**Comment by deeps96** [comment]
This has been already implemented during a hotfix-session (integration into overall system) in:
74b0a311cef332c3484e8f4e05989f50b6592c7b
24a973fa9a05e7add8efe831ed1ba1150bf0d6af
e44477d79c9b35c65d2bd6812b8aec234545c6a5

Open Tasks:
- [x] Write tests

**Comment by deeps96** [comment]
Pushed this to master by accident.
